language: go
go_import_path: github.com/minio/mc
os: linux
arch: ppc64le
dist: bionic
sudo: required
env: ARCH=ppc64le CGO_ENABLED=0 GO111MODULE=on

# Enable build cache
# https://restic.net/blog/2018-09-02/travis-build-cache
cache:
 directories:
   - $HOME/.cache/go-build
   - $HOME/gopath/pkg/mod
   - $HOME/go/pkg/mod

go: 1.14.x

before_script:
  # Add an IPv6 config - see the corresponding Travis issue
  # https://github.com/travis-ci/travis-ci/issues/8361
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6'; fi

before_install:
 - sudo apt install -y lftp
 - sudo apt install rpm
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then nvm install node ; fi

script:
  - python3 ftp_version.py
  - bash build.sh
  - bash release.sh

notifications:
  slack:
    rooms:
      - secure: "PmL3NisIMlEOllKA6ks3EB5Y26BzJdqlZKRxAaQIWlC/voRw47PYgnUGU4J9NhNcGwQMJZF+1kvlXgQ+/TXzQU9XDLhEZt/Y3BMgiuKK48doFUjVcPkgTE2bKFqvi/Jtd/0Di9p6Z+1HjxvUlJ0lW1krY3jSFolGInfTXlj6ktPSDxkdfa3gIkPsZz6DrAVoOW/XHFOzDdRsWRe8LJTj40FFqg8VK3eRvr2uv2rM1TH9+/G6umZPArsXiPLIrJP4dZ/1CU7kIVMwDkYEt55hopMQytnYGIqKmKN7ZDygAs73cDB0zGR/EXj+4GjXcVJf7+TNnoxMgaOeKQ8wrLkk/f3GPGUy9EJgHnhmeqQVTLMEeBnidQsKNXA18TGI9qlc9jpFy5qmRl4h0+T9Q7S3uMiP2UKzKy6/dJ9TPPMDiP8fOE7WZBAxBsTCW4ySib0KZ9hUiLLNWzAYocjs6BDHHD2/CXoEmY2o+R0k6TxystmnZtB1rzX8dsbI5N3qIUz2vNlmuaGQ2ITp1HB3rxBk/ABph9VuNQmscYFcIsDftAqCRl5CZSSYR/vuvs7zw/2qp2aWsiuQ241wHmnZHqbyVNhbByj9PkhlKSsm5AkGia11O3HS3cbeyLXipfCu3i4WMbgieebYvAXQrc/DnZrLFriu+/2Pd+3wcYrVB34Slak="
    on_success: change
    on_failure: change
